pipelines:
  - name: npm_build
  # Global configuration section for the entire pipeline
    configuration:
      environmentVariables:
        readOnly:
          Version: 1.0.$run_number
          dockerImage: 34.107.212.223/team1-docker/npm-app
    steps:
      - name: npm_compile
        type: NpmBuild
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: docker.bintray.io/jfrog/pipelines-u18node
                tag: "10.16.3"
          npmArgs:   install
          repositoryName:   team1-npm
          sourceLocation:   tutorial/step2-create-ui-pkg
          integrations:
            - name: artifactory
          inputResources:
            - name: orbitera_gitRepo_demo
        execution:
          onStart:
            - npm install shelljs



      - name: npm_publish
        type: NpmPublish
        configuration:
          repositoryName:       team1-npm
          forceXrayScan:        false
          autoPublishBuildInfo: true
          integrations:
            - name: artifactory
          inputSteps:
            - name: npm_compile
          outputResources:
            - name: npmBuildInfo


      - name: npm_scan
        type: XrayScan
        configuration:
          #inherits from bash
          waitUntilFinish: true
          inputResources:
            - name: npmBuildInfo        
              trigger: true
          outputResources: 
            - name: scanned_npmBuild_Info
       
         
            
                     
      - name: npm_promote
        type: PromoteBuild
        configuration:
          targetRepository:      team1-npm-staging-us 
          includeDependencies:   false   
          status:                Passed
          comment:               Artifact passed Xray Scan
          copy:                  true
          inputResources:
            - name:    scanned_npmBuild_Info    # optional
              trigger: true       
          outputResources:
            - name: promoted_npmBuild_Info

      - name: npm_docker_build
        type: DockerBuild
        configuration:
          dockerFileLocation: tutorial/step3-create-docker-multi-app
          dockerFileName: Dockerfile
       #   dockerImageName: ${dockerImage}
          dockerImageName: ${ArtIP}/team1-docker/npm-app
          dockerImageTag: ${Version}
          inputResources: 
            - name: orbitera_gitRepo_demo
            - name: npm_fileSpec
            - name: promoted_npmBuild_Info
              trigger: true
          integrations:
            - name: artifactory
        execution:
          onStart:
            - export ArtIP=$(echo ${int_artifactory_url}|awk -F '/' '{print $3}'|awk -F ':' '{print $1}')
            - mkdir -p tutorial/step3-create-docker-multi-app/package
          onSuccess:
            - echo "Congrats The Docker image was build"

          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"

      - name: Npm_docker_push
        type: DockerPush
        configuration:
          targetRepository:     team1-docker
          forceXrayScan:        false
          autoPublishBuildInfo: true
          integrations:
            - name:  artifactory
          inputSteps:
            - name: npm_docker_build
          outputResources:
            - name: docker_npmBuild_Info
